#!/bin/bash
## =========================================
GREEN='\033[0;32m'
RED='\033[0;31m'
IPVPS=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/scscp/permission/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $IPVPS | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $IPVPS \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/CandraVpnz"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6281573872702"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc
clear

ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10 )
CITY=$(curl -s ipinfo.io/city )
MYIP=$(curl -sS ipv4.icanhazip.com)
Name=$(curl -sS https://raw.githubusercontent.com/scscp/permission/main/ip | grep $MYIP | awk '{print $2}')
if [ "$res" = "Expired" ]; then
Exp="\e[36mExpired\033[0m"
else
Exp=$(curl -sS https://raw.githubusercontent.com/scscp/permission/main/ip | grep $MYIP | awk '{print $3}')
fi

# =========================================
# // Exporting URL Host
export MYIP=$( curl -s https://ipinfo.io/ip/ )
Name=$(curl -sS https://raw.githubusercontent.com/scscp/permission/main/ip | grep $MYIP | awk '{print $2}')
Exp=$(curl -sS https://raw.githubusercontent.com/scscp/permission/main/ip | grep $MYIP | awk '{print $3}')

# // Root Checking
if [ "${EUID}" -ne 0 ]; then
		echo -e "${EROR} Please Run This Script As Root User !"
		exit 1
fi

# // Exporting IP Address
export IP=$( curl -s https://ipinfo.io/ip/ )

clear

ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10 )
CITY=$(curl -s ipinfo.io/city )
MYIP=$(curl -sS ipv4.icanhazip.com)
nama=$(curl -sS https://raw.githubusercontent.com/scscp/permission/main/ip | grep $MYIP | awk '{print $2}')
if [ "$res" = "Expired" ]; then
Exp="\e[36mExpired\033[0m"
else
Exp=$(curl -sS https://raw.githubusercontent.com/scscp/permission/main/ip | grep $MYIP | awk '{print $3}')
fi

data_ip="https://raw.githubusercontent.com/scscp/permission/main/ip"
d2=$(date -d "$date_list" +"+%s")
d1=$(date -d "$Exp" +"+%s")
dayleft=$(( ($d1 - $d2) / 86400 ))

ssh=$(service ssh status | grep active | cut -d ' ' $stat)
if [ "$ssh" = "active" ]; then
ressh="${BBlue}ON${NC}"
else
ressh="${red}OFF${NC}"
fi
ngx=$(service nginx status | grep active | cut -d ' ' $stat)
if [ "$ngx" = "active" ]; then
resngx="${BBlue}ON${NC}"
else
resngx="${red}OFF${NC}"
fi
dbr=$(service dropbear status | grep active | cut -d ' ' $stat)
if [ "$dbr" = "active" ]; then
resdbr="${BBlue}ON${NC}"
else
resdbr="${red}OFF${NC}"
fi
v2r=$(service xray status | grep active | cut -d ' ' $stat)
if [ "$v2r" = "active" ]; then
resv2r="${BBlue}ON${NC}"
else
resv2r="${red}OFF${NC}"
fi
# STATUS SERVICE UDP CUSTOM
if [[ $udpc == "running" ]]; then
   udp2="${GB}[ ON ]${NC}${NC}"
else
   udp2="${RB}[ OFF ]${NC}"
fi
RED='\033[0;31m'
NC='\033[0m'
gray="\e[1;30m"
Blue="\033[36m"
GREEN='\033[0;32m'
grenbo="\e[92;1m"
YELL='\033[0;33m'
KONENG="\033[1;93m"
Dev="CANDRA-VPN-STORE"
ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10 ) 
CITY=$(curl -s ipinfo.io/city )
NS=$(cat /etc/xray/dns)
IPVPS=$(curl -s ipv4.icanhazip.com)
domain=$(cat /etc/xray/domain)
RAM=$(free -m | awk 'NR==2 {print $2}')
USAGERAM=$(free -m | awk 'NR==2 {print $3}')
MEMOFREE=$(printf '%-1s' "$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')")
LOADCPU=$(printf '%-0.00001s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")
MODEL=$(cat /etc/os-release | grep -w PRETTY_NAME | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/PRETTY_NAME//g')
CORE=$(printf '%-1s' "$(grep -c cpu[0-9] /proc/stat)")
Name="Candra"
DATEVPS=$(date +'%d/%m/%Y')
TIMEZONE=$(printf '%(%H:%M:%S)T')
SERONLINE=$(uptime -p | cut -d " " -f 2-10000)
if [ ! -e /etc/vmess ]; then
    mkdir -p /etc/vmess
    touch /etc/vmess/.vmess.db
fi
vms=$(cat /etc/vmess/.vmess.db)
if [[ $vms = "" ]]; then
    vm="0"
else
    vm=$(cat /etc/vmess/.vmess.db | grep "###" | wc -l)
fi

if [ ! -e /etc/vless ]; then
    mkdir -p /etc/vless
    touch /etc/vless/.vless.db
fi
vms=$(cat /etc/vless/.vless.db)
if [[ $vms = "" ]]; then
    vl="0"
else
    vl=$(cat /etc/vless/.vless.db | grep "###" | wc -l)
fi

if [ ! -e /etc/trojan ]; then
    mkdir -p /etc/trojan
    touch /etc/trojan/.trojan.db
fi
vms=$(cat /etc/trojan/.trojan.db)
if [[ $vms = "" ]]; then
    tr="0"
else
    tr=$(cat /etc/trojan/.trojan.db | grep "###" | wc -l)
fi
if [ ! -e /etc/shadowsocks ]; then
    mkdir -p /etc/shadowsocks
    touch /etc/shadowsocks/.shadowsocks.db
fi
vms=$(cat /etc/shadowsocks/.shadowsocks.db)
if [[ $vms = "" ]]; then
    ss="0"
else
    ss=$(cat /etc/shadowsocks/.shadowsocks.db | grep "###" | wc -l)
fi
if [ ! -e /etc/ssh ]; then
    mkdir -p /etc/ssh
    touch /etc/ssh/.ssh.db
fi
vms=$(cat /etc/ssh/.ssh.db)
if [[ $vms = "" ]]; then
    ssh="0"
else
    ssh=$(cat /etc/ssh/.ssh.db | grep "###" | wc -l)
fi
clear
echo -e "\033[1;93m┌─────────────────────────────────────────────────┐${NC}"
echo -e "\033[1;93m│ ${BGX}               king-stores               ${NC} ${NC}"
echo -e "\033[1;93m└─────────────────────────────────────────────────┘${NC}"
echo -e "\033[1;93m┌─────────────────────────────────────────────────┐${NC}"
echo -e "\033[1;93m│ ${NC}System OS${NC}     : ${NC}$MODEL${NC}"
echo -e "\033[1;93m│ ${NC}Server RAM${NC}    : ${NC}$RAM MB $NC"
echo -e "\033[1;93m│ ${NC}Uptime Server${NC} : ${NC}$SERONLINE${NC}"
echo -e "\033[1;93m│ ${NC}Core System${NC}   : ${NC}$CORE${NC}"
echo -e "\033[1;93m│ ${NC}Date${NC}          : ${NC}$DATEVPS${NC}"
echo -e "\033[1;93m│ ${NC}Time${NC}          : ${NC}$TIMEZONE${NC}"
echo -e "\033[1;93m│ ${NC}ISP ${NC}          : ${NC}$ISP${NC}"
echo -e "\033[1;93m│ ${NC}CITY${NC}          : ${NC}$CITY${NC}"
echo -e "\033[1;93m│ ${NC}IP VPS${NC}        : ${KONENG}$IPVPS${NC}"
echo -e "\033[1;93m│ ${NC}Domain${NC}        : ${KONENG}$domain${NC}"
echo -e "\033[1;93m│ ${NC}NS Domain${NC}     : $NS${NC}"
echo -e "\033[1;93m└─────────────────────────────────────────────────┘${NC}"
echo -e "\033[1;93m┌─────────────────────────────────────────────────┐${NC}"
echo -e "\033[1;93m│   ${Blue}XRAY${NC}: [${v2r}]     ${Blue}NGINX${NC}: [${ngx}${NC}]     ${Blue}HAPROXY${NC}: [${ngx}${NC}]  ${KONENG}${NC}"
echo -e "\033[1;93m└─────────────────────────────────────────────────┘${NC}"
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "\033[1;93m│\e[0m ${KONENG}SSH  VMESS   VLESS  TROJAN   SHADOWSOCKS$NC"
echo -e "\033[1;93m│\e[0m ${Blue} $ssh     $vm       $vl      $tr           $ss   $NC"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e "\033[1;93m   ┌───────────────────────────────────────────┐${NC}"
echo -e "\033[1;93m   │  ${NC}Version     : v1.0.7 LTS${NC}"
echo -e "\033[1;93m   │  ${NC}Author Name : ${KONENG}$Dev${NC}"
echo -e "\033[1;93m   │  ${NC}Client Name : ${RED}$nama${NC}"
echo -e "\033[1;93m   │  ${NC}Expiry In   : ${RED}$Exp${NC}$dayleft Days ${NC}"
echo -e "\033[1;93m   └───────────────────────────────────────────┘${NC}"
echo -e "\033[1;93m┌─────────────────────────────────────────────────┐${NC}"
echo -e "\033[1;93m│  ${KONENG}[1] ${NC}☞ SSH&OVPN ${NC}""    \033[33m  ${KONENG}[6] ${NC}☞ FEATURES ${NC}"
echo -e "\033[1;93m│  ${KONENG}[2] ${NC}☞ VMESS ${NC}"        "      \033[33m  ${KONENG}[7] ${NC}☞ REBOOT ${NC}"
echo -e "\033[1;93m│  ${KONENG}[3] ${NC}☞ VLESS ${NC}"         "      \033[33m  ${KONENG}[8] ${NC}☞ ATUR BOT NOTIF ${NC}"
echo -e "\033[1;93m│  ${KONENG}[4] ${NC}☞ TROJAN ${NC}"     "     \033[33m  ${KONENG}[9] ${NC}☞ CHANGE BANNER ${NC}"
echo -e "\033[1;93m│  ${KONENG}[5] ${NC}☞ SHADOWSHOCK ${NC}"     "\033[33m  ${KONENG}[10]${NC}☞ INFO PORT ${NC}"
echo -e "\033[1;93m│  ${KONENG}[11] ${NC}☞ MENU IP ${NC}"
echo -e "\033[1;93m└─────────────────────────────────────────────────┘${NC}"
echo -e ""
read -p " Select Options [ 1 - 6 or x exit ] : " menu
case $menu in
1)
    ssh
    ;;
2)
    vmess
    ;;
3)
    vless
    ;;
4)
    trojan
    ;;
5)
    shadowsocks
    ;;
6)
    utility 
    ;;
7)
    reboot 
    ;;
8)
    add-bot-notif
    ;;
9)
    nano /etc/issue.net
    ;;

10)
    portin
    ;;
11)
    menu-ip
    ;;

*)
    menu
    ;;
esac
