#!/bin/bash
clear
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
clear
RED='\033[0;31m'
NC='\e[0m'
gray="\e[1;30m"
Blue="\033[1;36m"
GREEN='\033[0;32m'
grenbo="\033[1;95m"
YELL='\033[1;33m'
BGX="\033[42m"
UPDATE="https://raw.githubusercontent.com/JurigVPN/scupdate/rizki/"
BOT="https://raw.githubusercontent.com/JurigVPN/scupdate/rizki/"
clear
echo -e "\033[96m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e " \e[1;971m                      MENU SSH                \e[0m"
echo -e "\033[96m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "  ${grenbo}[1]${NC}${YELL} Create SSH OVPN Account${NC}"
echo -e "  ${grenbo}[2]${NC}${YELL} Create Trial SSH OVPN Account${NC}"
echo -e "  ${grenbo}[3]${NC}${YELL} Delete SSH OVPN Account${NC}"
echo -e "  ${grenbo}[4]${NC}${YELL} Renew SSH OVPN Account${NC}"
echo -e "  ${grenbo}[5]${NC}${YELL} Login SSH OVPN Account${NC}"
echo -e "  ${grenbo}[6]${NC}${YELL} Member SSH OVPN Account${NC}"
echo -e "  ${grenbo}[7]${NC}${YELL} Tendang Multi Login SSH OVPN Account${NC}"
echo -e ""
echo -e "  ${grenbo}[0]${NC}${YELL} Back To Menu${NC}"
echo -e ""
read -p "  Select From Options [ 1 - 8 or 0 ] : " menu
case $menu in
1)
    add-ssh
    ;;
2)
    triall-ssh
    ;;
3)
    del-ssh
    ;;
4)
    renew-ssh
    ;;
5)
    cek-ssh
    ;;
6)
    list-akun-ssh
    ;;
7)
    tendang
    ;;
0)
    menu
    ;;
*)
    menu
    ;;
esac
