#!/bin/bash
clear
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
clear
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
clear
grenbo="\e[92;1m"
NC='\033[0m'
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e " \e[1;97;101m              MENU TROJAN               \e[0m"
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[1;93m  ${grenbo}1.${NC} \033[0;36mCreating a Trojan Account${NC}"
echo -e "\033[1;93m  ${grenbo}2.${NC} \033[0;36mTriall a Trojan Account${NC}"
echo -e "\033[1;93m  ${grenbo}3.${NC} \033[0;36mDetails Trojan Account${NC}"
echo -e "\033[1;93m  ${grenbo}4.${NC} \033[0;36mDelete Trojan Account${NC}"
echo -e "\033[1;93m  ${grenbo}5.${NC} \033[0;36mRenew Trojan Account${NC}"
echo -e "\033[1;93m  ${grenbo}6.${NC} \033[0;36mCheck Trojan login Account${NC}"
echo -e "\033[1;93m  ${grenbo}7.${NC} \033[0;36mCheck Trojan Usage Account${NC}"
echo -e "\033[1;93m"
echo -e "\033[1;93m  ${grenbo}0.${NC} \033[0;36mBack To Menu${NC}"
echo -e ""
read -p "Select From Options [ 1 - 7 or 0 ] : " menu
case $menu in
1)
    add-tr
    ;;
2) 
    triall-tr
    ;;
3)
    user-tr
    ;;
4)
    del-tr
    ;;
5)
    renew-tr
    ;;
6)
    cek-tr
    ;;
7)
    usage-akun-xray-trojan
    ;;
0)
    menu
    ;;
*)
    menu
    ;;
esac
