#!/bin/bash
clear
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
clear
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
clear
grenbo="\e[92;1m"
NC='\033[0m'
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e " \e[1;97;101m               MENU VLESS               \e[0m"
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[1;93m  ${grenbo}1.${NC} \033[0;36mCreating Vless Account${NC}"
echo -e "\033[1;93m  ${grenbo}2.${NC} \033[0;36mTriall Vless Account${NC}"
echo -e "\033[1;93m  ${grenbo}3.${NC} \033[0;36mDetails Vless Account${NC}"
echo -e "\033[1;93m  ${grenbo}4.${NC} \033[0;36mDelete Vless Account${NC}"
echo -e "\033[1;93m  ${grenbo}5.${NC} \033[0;36mRenew Vless Account${NC}"
echo -e "\033[1;93m  ${grenbo}6.${NC} \033[0;36mLogim Vless Account${NC}"
echo -e "\033[1;93m  ${grenbo}7.${NC} \033[0;36mUsage Vless Account${NC}"
echo -e "\033[1;93m"
echo -e "\033[1;93m  ${grenbo}0.${NC} \033[0;36mBack To Menu${NC}"
echo -e ""
read -p "Select From Options [ 1 - 7 or 0 ] : " menu
case $menu in
1)
    add-vless
    ;;
2) 
    triall-vless
    ;;
3)
    user-vless
    ;;
4)
    del-vless
    ;;
5)
    renew-vless
    ;;
6)
    cek-vless
    ;;
7)
    usage-akun-xray-vless
    ;;
0)
    menu
    ;;
*)
    menu
    ;;
esac
