#!/bin/bash
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
clear
##----- Auto Remove Vmess
data=($(cat /etc/xray/config.json | grep '^#vm#' | cut -d ' ' -f 2 | sort | uniq))
now=$(date +"%Y-%m-%d")
for user in "${data[@]}"; do
    exp=$(grep -w "^#vm# $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    expvm=$(grep -E "^#vm# " "/etc/vmess/.vmess.db" | cut -d ' ' -f 3  | sort | uniq)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$expvm" +%s)
    d3=$(date -d "$now" +%s)
    exp2=$(((d1 - d3) / 86400))
    exp3=$(((d2 - d3) / 86400))
    if [[ "$exp2" -le "0" ]]; then
        sed -i "/^#vm# $user $exp/,/^},{/d" /etc/vmess/.vmess.db
        sed -i "/^#vm# $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "/^#vm# $user $exp/,/^},{/d" /etc/xray/config.json
        rm -rf /var/www/html/vmess-$user.txt
    fi
    if [[ "$exp3" -le "0" ]]; then
        sed -i "/^#vm# $user $exp/,/^},{/d" /etc/vmess/.vmess.db
        sed -i "/^#vm# $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "/^#vm# $user $exp/,/^},{/d" /etc/xray/config.json
        rm -rf /var/www/html/vmess-$user.txt
    fi
done

#----- Auto Remove Vless
data=($(cat /etc/xray/config.json | grep '^#vl#' | cut -d ' ' -f 2 | sort | uniq))
now=$(date +"%Y-%m-%d")
for user in "${data[@]}"; do
    exp=$(grep -w "^#vl# $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    expvl=$(grep -E "^#vl# " "/etc/vless/.vless.db" | cut -d ' ' -f 3  | sort | uniq)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$expvl" +%s)
    d3=$(date -d "$now" +%s)
    exp2=$(((d1 - d3) / 86400))
    exp3=$(((d2 - d3) / 86400))
    if [[ "$exp2" -le "0" ]]; then
        sed -i "/^#vl# $user $exp/,/^},{/d" /etc/vless/.vless.db
        sed -i "/^#vl# $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "/^#vl# $user $exp/,/^},{/d" /etc/xray/config.json
        rm -rf /var/www/html/vless-$user.txt
    fi
    if [[ "$exp3" -le "0" ]]; then
        sed -i "/^#vl# $user $exp/,/^},{/d" /etc/vless/.vless.db
        sed -i "/^#vl# $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "/^#vl# $user $exp/,/^},{/d" /etc/xray/config.json
        rm -rf /var/www/html/vless-$user.txt
    fi
done

#----- Auto Remove Trojan
data=($(cat /etc/xray/config.json | grep '^#tr#' | cut -d ' ' -f 2 | sort | uniq))
now=$(date +"%Y-%m-%d")
for user in "${data[@]}"; do
    exp=$(grep -w "^#tr# $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    exptr=$(grep -E "^#tr# " "/etc/trojan/.trojan.db" | cut -d ' ' -f 3  | sort | uniq)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$exptr" +%s)
    d3=$(date -d "$now" +%s)
    exp2=$(((d1 - d3) / 86400))
    exp3=$(((d2 - d3) / 86400))
    if [[ "$exp2" -le "0" ]]; then
        sed -i "/^#tr# $user $exp/,/^},{/d" /etc/trojan/.trojan.db
        sed -i "/^#tr# $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "/^#tr# $user $exp/,/^},{/d" /etc/xray/config.json
        rm -rf /var/www/html/trojan-$user.txt
    fi
    if [[ "$exp3" -le "0" ]]; then
        sed -i "/^#tr# $user $exp/,/^},{/d" /etc/trojan/.trojan.db
        sed -i "/^#tr# $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "/^#tr# $user $exp/,/^},{/d" /etc/xray/config.json
        rm -rf /var/www/html/trojan-$user.txt
    fi
done

#----- Auto Remove SS
data=($(cat /etc/xray/config.json | grep '^#ss#' | cut -d ' ' -f 2 | sort | uniq))
now=$(date +"%Y-%m-%d")
for user in "${data[@]}"; do
    exp=$(grep -w "^#ss# $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    expss=$(grep -E "^#ss# " "/etc/shadowsocks/.shadowsocks.db" | cut -d ' ' -f 3  | sort | uniq)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$expss" +%s)
    d3=$(date -d "$now" +%s)
    exp2=$(((d1 - d3) / 86400))
    exp3=$(((d2 - d3) / 86400))
    if [[ "$exp2" -le "0" ]]; then
        sed -i "/^#tr# $user $exp/,/^},{/d" /etc/shadowsocks/.shadowsocks.db
        sed -i "/^#ss# $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "/^#ss# $user $exp/,/^},{/d" /etc/xray/config.json
        rm -rf /var/www/html/ss-$user.txt
    fi
    if [[ "$exp3" -le "0" ]]; then
        sed -i "/^#tr# $user $exp/,/^},{/d" /etc/shadowsocks/.shadowsocks.db
        sed -i "/^#ss# $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "/^#ss# $user $exp/,/^},{/d" /etc/xray/config.json
        rm -rf /var/www/html/ss-$user.txt
    fi
done
systemctl restart xray

##------ Auto Remove SSH
hariini=$(date +%d-%m-%Y)
cat /etc/shadow | cut -d: -f1,8 | sed /:$/d >/tmp/expirelist.txt
totalaccounts=$(cat /tmp/expirelist.txt | wc -l)
for ((i = 1; i <= $totalaccounts; i++)); do
    tuserval=$(head -n $i /tmp/expirelist.txt | tail -n 1)
    username=$(echo $tuserval | cut -f1 -d:)
    userexp=$(echo $tuserval | cut -f2 -d:)
    userexpireinseconds=$(($userexp * 86400))
    tglexp=$(date -d @$userexpireinseconds)
    tgl=$(echo $tglexp | awk -F" " '{print $3}')
    while [ ${#tgl} -lt 2 ]; do
        tgl="0"$tgl
    done
    while [ ${#username} -lt 15 ]; do
        username=$username" "
    done
    bulantahun=$(echo $tglexp | awk -F" " '{print $2,$6}')
    todaystime=$(date +%s)
    if [ $userexpireinseconds -ge $todaystime ]; then
        :
    else
        userdel --force $username
        sed -i "/^#ssh# $user $exp/,/^},{/d" /etc/ssh/.ssh.db
    fi
done
systemctl reload ssh

echo -e " done delet all expired "
